use Mix.Config

################ API ####################
# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :api, ApiWeb.Endpoint,
  http: [:inet6, port: System.get_env("PORT") || 8080],
  url: [host: "", port: 8080],
  cache_static_manifest: "priv/static/cache_manifest.json"

################ FRONTEND ####################
# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :frontend, FrontendWeb.Endpoint,
  http: [:inet6, port: System.get_env("PORT") || 4000],
  url: [host: ""],
  cache_static_manifest: "priv/static/cache_manifest.json"

################ META ####################
# Do not print debug messages in production
config :logger, level: :info

# Import prod.secret.exs, which loads secrets and
# configuration from environment variables.
import_config "prod.secret.exs"
